"use client";

import React from "react";
import { BookOpen, Quote, FileText, Sparkles, Compass } from "lucide-react";

export interface ExampleTemplate {
  id: string;
  title: string;
  type: string;
  excerpt: string;
  content: string;
  icon: React.ReactNode;
}

interface ExampleGalleryProps {
  onSelect: (title: string, content: string) => void;
}

export function ExampleGallery({ onSelect }: ExampleGalleryProps) {
  const examples: ExampleTemplate[] = [
    {
      id: "quote",
      title: "Inspirational Quote",
      type: "Inspirational",
      excerpt: "The only limit to our realization of tomorrow will be our doubts of today...",
      content: "<p>The only limit to our realization of tomorrow will be our doubts of today. Let us move forward with strong and active faith, for the future belongs to those who believe in the beauty of their dreams.</p>",
      icon: <Quote className="w-5 h-5 text-purple-400" />
    },
    {
      id: "story",
      title: "Story Opening",
      type: "Narrative",
      excerpt: "The train slipped into the station under a heavy shroud of mist. Julian pulled his collar...",
      content: "<p>The train slipped into the station under a heavy shroud of mist. Julian pulled his collar tight against the damp cold, searching the dimly lit platform for the face he hadn't seen in ten years.</p>",
      icon: <Compass className="w-5 h-5 text-indigo-400" />
    },
    {
      id: "poem",
      title: "Silent Whispers",
      type: "Poem",
      excerpt: "The stars grow cold, the shadows fall, a silent whisper through the hall...",
      content: "<p>The stars grow cold, the shadows fall,<br>A silent whisper through the hall.<br>The leaves drift down in quiet grace,<br>Time leaves no footprint in this place.</p>",
      icon: <Sparkles className="w-5 h-5 text-rose-400" />
    },
    {
      id: "speech",
      title: "A New Threshold",
      type: "Speech",
      excerpt: "We stand today at the threshold of a new era. The challenges before us are great...",
      content: "<p>We stand today at the threshold of a new era. The challenges before us are great, but our collective resolve is greater. Let us choose hope over fear, and unity over division, as we write the next chapter of our history together.</p>",
      icon: <FileText className="w-5 h-5 text-amber-400" />
    },
    {
      id: "reflection",
      title: "The Quiet River",
      type: "Reflection",
      excerpt: "Time is a quiet river that carries us along, sometimes gently, sometimes in torrents...",
      content: "<p>Time is a quiet river that carries us along, sometimes gently, sometimes in torrents. We look back at the banks we have passed, wishing we could linger in the quiet pools of yesterday, yet the current always pulls us forward into the unknown sea.</p>",
      icon: <BookOpen className="w-5 h-5 text-emerald-400" />
    }
  ];

  return (
    <div className="w-full max-w-4xl mx-auto py-8 px-6">
      <div className="mb-8 text-center sm:text-left">
        <h2 className="text-xl font-medium tracking-tight text-zinc-100 font-serif">Inspiration Gallery</h2>
        <p className="text-xs text-zinc-400 mt-1 max-w-xl">
          Select a writing starter generated by the model. Open it to begin co-writing with Verra.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {examples.map((item) => (
          <button
            key={item.id}
            onClick={() => onSelect(item.title, item.content)}
            className="flex flex-col text-left p-5 rounded-xl border border-zinc-800/40 bg-zinc-900/10 hover:bg-zinc-900/30 hover:border-zinc-700/40 transition-all duration-200 group relative overflow-hidden outline-none cursor-pointer"
          >
            <div className="flex items-center gap-3 mb-3">
              <div className="p-2 rounded-lg bg-zinc-900/50 border border-zinc-800/50 group-hover:border-zinc-700/50 transition-colors">
                {item.icon}
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-mono tracking-wider uppercase">{item.type}</span>
                <h3 className="text-sm font-medium text-zinc-200 group-hover:text-white transition-colors">{item.title}</h3>
              </div>
            </div>
            
            <p className="text-xs text-zinc-400 leading-relaxed font-serif flex-1">
              "{item.excerpt}"
            </p>

            <div className="mt-4 flex items-center justify-end text-[10px] text-zinc-500 group-hover:text-zinc-300 font-medium transition-colors gap-1.5">
              <span>Write from this template</span>
              <span className="transition-transform group-hover:translate-x-0.5">→</span>
            </div>
            
            {/* Subtle glow border hover */}
            <div className="absolute inset-0 border border-transparent group-hover:border-purple-500/10 rounded-xl pointer-events-none" />
          </button>
        ))}
      </div>
    </div>
  );
}
