"use client";

import React from "react";
import { BookOpen, Quote, FileText, Sparkles, Compass } from "lucide-react";

export interface ExampleTemplate {
  id: string;
  title: string;
  type: string;
  excerpt: string;
  content: string;
  icon: React.ReactNode;
}

interface ExampleGalleryProps {
  onSelect: (title: string, content: string) => void;
}

export function ExampleGallery({ onSelect }: ExampleGalleryProps) {
  const examples: ExampleTemplate[] = [
    {
      id: "quote",
      title: "The Future",
      type: "Model Generated",
      excerpt: "The future belongs to those who never stop learning...",
      content: "<p>The future belongs <span class=\"verra-glow-text\" data-candidates='[]'>to those who never stop learning.</span></p>",
      icon: <Quote className="w-5 h-5 text-purple-400" />
    },
    {
      id: "story",
      title: "Every Challenge",
      type: "Model Generated",
      excerpt: "Every challenge begins with a single step into the unknown...",
      content: "<p>Every challenge begins <span class=\"verra-glow-text\" data-candidates='[]'>with a single step into the unknown.</span></p>",
      icon: <Compass className="w-5 h-5 text-indigo-400" />
    },
    {
      id: "poem",
      title: "Silence of the Forest",
      type: "Model Generated",
      excerpt: "In the silence of the forest, the trees whisper ancient secrets...",
      content: "<p>In the silence of the forest, <span class=\"verra-glow-text\" data-candidates='[]'>the trees whisper ancient secrets.</span></p>",
      icon: <Sparkles className="w-5 h-5 text-rose-400" />
    },
    {
      id: "speech",
      title: "Greatest Lessons",
      type: "Model Generated",
      excerpt: "The greatest lessons are often learned from our worst mistakes...",
      content: "<p>The greatest lessons <span class=\"verra-glow-text\" data-candidates='[]'>are often learned from our worst mistakes.</span></p>",
      icon: <FileText className="w-5 h-5 text-amber-400" />
    }
  ];

  return (
    <div className="w-full max-w-4xl mx-auto py-8 px-6">
      <div className="mb-8 text-center sm:text-left">
        <h2 className="text-xl font-medium tracking-tight text-zinc-100 font-serif">Inspiration Gallery</h2>
        <p className="text-xs text-zinc-400 mt-1 max-w-xl">
          Select a writing starter. The highlighted portions represent authentic predictions generated by Verra's recurrent language model.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {examples.map((item) => (
          <button
            key={item.id}
            onClick={() => onSelect(item.title, item.content)}
            className="flex flex-col text-left p-5 rounded-xl border border-zinc-850 bg-zinc-900/10 hover:bg-zinc-900/35 hover:border-purple-800/25 transition-all duration-200 group relative overflow-hidden outline-none cursor-pointer"
          >
            <div className="flex items-center gap-3 mb-3">
              <div className="p-2 rounded-lg bg-zinc-950/60 border border-zinc-900/50 group-hover:border-purple-900/20 transition-colors">
                {item.icon}
              </div>
              <div>
                <span className="text-[9px] text-purple-400 font-mono tracking-wider uppercase font-semibold">{item.type}</span>
                <h3 className="text-sm font-medium text-zinc-200 group-hover:text-white transition-colors">{item.title}</h3>
              </div>
            </div>
            
            <p className="text-xs text-zinc-400 leading-relaxed font-serif flex-1">
              "{item.excerpt}"
            </p>

            <div className="mt-4 flex items-center justify-end text-[10px] text-zinc-550 group-hover:text-zinc-300 font-medium transition-colors gap-1.5">
              <span>Co-write from this starter</span>
              <span className="transition-transform group-hover:translate-x-0.5">→</span>
            </div>
            
            {/* Subtle glow border hover */}
            <div className="absolute inset-0 border border-transparent group-hover:border-purple-500/10 rounded-xl pointer-events-none" />
          </button>
        ))}
      </div>
    </div>
  );
}
